services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow  # use common image
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'mysecretkey'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/shared/simple_auth_manager_passwords.json
      AIRFLOW__DAG_PROCESSOR__DAG_BUNDLE_CONFIG_LIST: >-
        [
          {
            "name": "dags-folder",
            "classpath": "airflow.dag_processing.bundles.local.LocalDagBundle",
            "kwargs": {"path": "/opt/airflow/dags"}
          }
        ]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./shared-data:/opt/airflow/shared
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate;
        airflow api-server
      "

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow  # use common image
    depends_on:
      - airflow-apiserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./shared-data:/opt/airflow/shared
    command: >
      bash -c "
        echo 'â³ Waiting for airflow api-server initilize db ...';
        sleep 10;

        echo 'Admin user password:'
        cat /opt/airflow/shared/simple_auth_manager_passwords.json;

        echo 'ðŸš€ Starting Airflow Scheduler...';
        airflow scheduler
      "

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    depends_on:
      - postgres
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/artifacts
    ports:
      - "5000:5000"
    command: >
      bash -c "
        echo 'Creating MLflow DB if not exists...';
        
        psql postgresql://airflow:airflow@postgres:5432/airflow -c \"SELECT 'CREATE DATABASE mlflow' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mlflow')\\gexec\";
        
        mlflow server
              --backend-store-uri postgresql://airflow:airflow@postgres:5432/mlflow
              --default-artifact-root /mlflow/artifacts
              --host 0.0.0.0
              --port 5000
      "


volumes:
  postgres-db-volume: